version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
  psn-notification-ms:
    image: psn-notification-ms
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on: 
      - rabbitmq
  psn-notification-ws-ms:
    image: psn-notification-ws-ms
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on: 
      - rabbitmq