version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "4402:5672"
      - "4403:15672"
    env_file:
      - .env
    networks:
      - psn_network

  psn-notification-ms:
    image: psn-notification-ms
    build: ../psn-notification-ms
    env_file:
      - ../psn-notification-ms/.env
    ports:
      - "4400:4400"
    depends_on: 
      - rabbitmq
    networks:
      - psn_network
      
  psn-notification-ws-ms:
    image: psn-notification-ws-ms
    build: .
    env_file:
      - .env
    ports:
      - "4401:4401"
    depends_on: 
      - rabbitmq
    networks:
      - psn_network

networks:
  psn_network:
    external: true